---
type: showroom

# Set the left column width to 30%
default_width: 30
# Persist the URL state so browser refresh doesn't reset the UI
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
- name: OpenShift Console
  url: 'https://console-openshift-console.${DOMAIN}'
- name: Red Hat Advanced Cluster Security
  url: 'https://central-stackrox.${DOMAIN}'
- name: Red Hat Quay
  url: 'https://quay.${DOMAIN}'
- name: Terminal
  path: /wetty
  port: 443
